import test from 'node:test';
import assert from 'node:assert/strict';
import {Q, defaultState, validateImportedState, dimensionScores, computeConcepts} from '../model.js';
import {applyChanges,deriveState} from '../worker.ts';
import {editableChanges,mergePending,FoundrySync} from '../shared-sync.js';
import {buildInsights} from '../insights.js';

function fixture(value=4){const state=structuredClone(defaultState);state.answers=state.answers.map(()=>Object.fromEntries(Q.map(q=>[q.id,q.type==='scale'?value:q.type==='multi'?[q.options[0]]:'A meaningful answer'])));return deriveState(state)}
const principal={founder:1,admin:true};
const operation=(state,path,value)=>{let current=state;for(const key of path)current=current?.[key];return {path,expected:current===undefined?{exists:false}:{exists:true,value:structuredClone(current)},value}};

test('96-question export contract accepts all three independently populated profiles',()=>{const state=fixture();assert.equal(Q.length,96);assert.equal(Q.filter(q=>q.type==='scale').length,88);assert.deepEqual(validateImportedState(state),state);assert(state.answers.every(a=>Object.keys(a).length===96))});
test('zero discipline and campaign values remain zero and lower concept scores',()=>{const state=fixture(1),dims=dimensionScores(state);assert.equal(dims.scopecontrol.score,0);assert.equal(dims.pitchability.score,0);const black=computeConcepts(state).find(c=>c.id==='c0');assert.equal(black.feasibility,68);assert.equal(black.campaign,79)});
test('a founder edit preserves every other founder and refreshes derived concepts',()=>{const state=fixture();const next=applyChanges(state,[operation(state,['answers',1,'q4'],7)],principal);assert.deepEqual(next.answers[0],state.answers[0]);assert.deepEqual(next.answers[2],state.answers[2]);assert.equal(next.answers[1].q4,7);assert.notDeepEqual(next.concepts,state.concepts)});
test('same-field conflict is rejected instead of overwriting another device',()=>{const state=fixture(),change=operation(state,['answers',1,'q4'],7);state.answers[1].q4=6;assert.throws(()=>applyChanges(state,[change],principal),e=>e.status===409)});
test('separate founders can merge changes based on the same initial dataset',()=>{const state=fixture();const a=operation(state,['answers',0,'q4'],6),b=operation(state,['answers',2,'q4'],7);const next=applyChanges(applyChanges(state,[a],{founder:0,admin:false}),[b],{founder:2,admin:false});assert.equal(next.answers[0].q4,6);assert.equal(next.answers[2].q4,7)});
test('a founder cannot edit another founder, shared settings, or market assessments',()=>{const state=fixture();for(const path of [['answers',1,'q4'],['founders',1,'name'],['shared','mvpBudget'],['market','demand']])assert.throws(()=>applyChanges(state,[operation(state,path,7)],{founder:0,admin:false}),e=>e.status===403)});
test('invalid answer values never pass backend validation',()=>{const state=fixture();for(const value of [0,8,'7',null])assert.throws(()=>applyChanges(state,[operation(state,['answers',1,'q4'],value)],principal),e=>e.status===400)});
test('a vote creates neutral defaults without allowing changes to another founder vote',()=>{const state=fixture();const next=applyChanges(state,[operation(state,['votes','c0',1],5)],principal);assert.deepEqual(next.votes.c0,[3,5,3]);assert.throws(()=>applyChanges(next,[operation(next,['votes','c0',0],1)],principal),e=>e.status===403)});
test('first votes from different founders merge despite materialized neutral slots',()=>{const state=fixture();const first=operation(state,['votes','c0',0],5),second=operation(state,['votes','c0',1],4);const next=applyChanges(applyChanges(state,[first],{founder:0,admin:false}),[second],principal);assert.deepEqual(next.votes.c0,[5,4,3]);assert.throws(()=>applyChanges(next,[second],principal),e=>e.status===409)});
test('client diff sends only owned fields and excludes all derived outputs',()=>{const before=fixture(),after=structuredClone(before);after.answers[0].q4=7;after.answers[1].q4=6;after.market.score=99;after.concepts[0].fit=100;const changes=editableChanges(before,after,principal);assert.deepEqual(changes.map(c=>c.path),[['answers',1,'q4']])});
test('offline typing coalesces one field and preserves its first conflict check',()=>{const state=fixture(),first=operation(state,['answers',1,'q91'],'a');let pending=[];for(let i=0;i<1000;i++)pending=mergePending(pending,[{...first,expected:{exists:true,value:i?'a'.repeat(i):first.expected.value},value:'a'.repeat(i+1)}]);assert.equal(pending.length,1);assert.deepEqual(pending[0].expected,first.expected);assert.equal(pending[0].value.length,1000);assert.deepEqual(mergePending(pending,[{...first,value:first.expected.value}]),[])});
test('a delayed old poll cannot replace a newer confirmed save',()=>{const state=fixture(),updates=[],sync=new FoundrySync({base:'https://example.com',onState:data=>updates.push(data),onStatus:()=>{},onAccess:()=>{}});const changed=structuredClone(state);changed.answers[1].q4=7;assert.equal(sync.apply({version:12,updatedAt:'2026-10-08',data:changed}),true);assert.equal(sync.apply({version:11,updatedAt:'2026-10-08',data:state}),false);assert.equal(sync.version,12);assert.equal(sync.snapshot.answers[1].q4,7);assert.equal(updates.length,1)});
test('research applicability changes when preferences change; sources remain dated',()=>{const state=fixture(),research={titles:[],baselineAnswers:structuredClone(state.answers)};assert.equal(buildInsights(state,research).researchCurrent,true);state.answers[1].q4=7;assert.equal(buildInsights(state,research).researchCurrent,false)});
test('invalid or incompatible exports are rejected, including injected fields',()=>{const state=fixture();state.answers[0].unknown=7;assert.throws(()=>validateImportedState(state));delete state.answers[0].unknown;state.answers[0].q89=['Invalid option'];assert.throws(()=>validateImportedState(state))});
